name: Validate Projects Data

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run validation script
        run: go run validate.go
